trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build test'
  - script: |
      ./build.sh
    displayName: Build project artifacts
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITADEV2-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"dataservices.azurecr.io", "id" : "/subscriptions/675d7977-79af-4b94-b0bd-26d4095a4ffb/resourceGroups/ITA-MSDataServices-Dev-East1/providers/Microsoft.ContainerRegistry/registries/dataservices"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: Build Docker image
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITADEV2-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"dataservices.azurecr.io", "id" : "/subscriptions/675d7977-79af-4b94-b0bd-26d4095a4ffb/resourceGroups/ITA-MSDataServices-Dev-East1/providers/Microsoft.ContainerRegistry/registries/dataservices"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Push services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: Push Docker image