kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ita-dataloader
  namespace: mdsnamespace
  labels:
    app: ita-dataloader
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ita-dataloader
    spec:
      containers:
      - name: ita-dataloader
        image: itadevacr.azurecr.io/ita-dataloader:#{Release.Artifacts._InternationalTradeAdministration.ita-dataloader.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: AZURE_STORAGE_ACCOUNT
            value: #{STORAGE-ACCOUNT-DEV}#
          - name: AZURE_STORAGE_ACCOUNT_KEY
            value: #{STORAGE-ACCOUNT-KEY-DEV}#
          - name: AZURE_OAUTH_CLIENT_ID
            value: #{OAUTH-CLIENT-ID}#
          - name: AZURE_OAUTH_CLIENT_SECRET
            value: #{OAUTH-CLIENT-SECRET}#
          - name: AZURE_OAUTH_TENANT_ID
            value: #{OAUTH-TENANT-ID}#
          - name: DATAFACTORY_CLIENT_ID
            value: #{DATAFACTORY-CLIENT-ID-DEV}#
          - name: DATAFACTORY_CLIENT_SECRET
            value: #{DATAFACTORY-CLIENT-SECRET-DEV}#
          - name: DATAFACTORY_NAME
            value: #{DATAFACTORY-NAME-DEV}#
          - name: DATAFACTORY_RESOURCE_GROUP
            value: #{DATAFACTORY-RESOURCE-GROUP-DEV}#
          - name: AZURE_SUBSCRIPTION_ID
            value: #{SUBSCRIPTION-ID-DEV}#
          - name: AZURE_TENANT_ID
            value: #{TENANT-ID-DEV}#
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: BUILD_ID
            value: "#{Release.Artifacts._InternationalTradeAdministration.ita-dataloader.BuildId}#"
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-dataloader
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: ita-dataloader
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: ita-dataloader
  namespace: mdsnamespace
spec:
  rules:
    - host: dataloader-dev.trade.gov
      http:
        paths:
          - path: /
            backend:
              serviceName: ita-dataloader
              servicePort: 80
  tls:
    - secretName: trade-gov-tls-secret
